Add files via upload
thoth-tech/ThothTech-Documentation-Website pull request #114
Opened 2024-11-19 03:55 UTC by s223552468

This is a file telling about local setup ,where we can learn how to access and use ontrack planner board, working on tickets and doing the PR for comiting changes in the tickets.

# Description
This pull request adds a detailed guide for setting up the local development environment, accessing and using the OnTrack Planner Board, working on tickets, and creating pull requests for committing changes associated with tickets.

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist

- [ ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

2024-11-21 01:08 UTC, Ashdeore approved these changes
I have reviewed the files in this pull request and found them to be a clear and detailed guide. They explain how to set up the local development environment, use the OnTrack Planner Board, work on tickets, and create pull requests for changes.
The document is well-organized, making it easy for new students to follow and understand everything before starting their work. It’s a helpful resource to ensure they can get started smoothly and contribute effectively.
Great job on creating this guide!
@s223552468
![2024-11-21 12 05 01](https://github.com/user-attachments/assets/4f54e269-cfba-4a4f-b63c-6cb4d97956c7)

2024-11-21 12:50 UTC, Shounaks requested changes
I believe the image urls are broken, can you check once again?

2024-11-21 15:07 UTC, s223552468 commented
Hi @Shounaks Now I have added the Image Urls correctly in the Public Folder.

2024-11-21 16:28 UTC, Shounaks approved these changes
LGTM! 👍

2025-03-13 09:39 UTC, aNebula approved these changes

2025-03-13 09:39 UTC, merged