Create team-members-t1-2024.md
thoth-tech/ThothTech-Documentation-Website pull request #61
Opened 2024-03-25 06:04 UTC by CchristiNana

# Description

_Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change._

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist

- [ ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

2024-03-25 10:13 UTC, CchristiNana commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update Team Member T1 2024 (Documentation Website)](https://trello.com/c/bNiiYJLQ/172-update-team-member-t1-2024-documentation-website)

2024-04-02 07:06 UTC, omckeon requested changes
In the SplashKit Team:
Please update a few names that are incorrect.

Rest looks good.

2024-04-02 07:06 UTC, omckeon commented on src/content/docs/teams-and-leadership/team-members-t1-2024.md
> +| Hayden Hughes            | Team member  | Code, Documentation                  |
Update this name to be: Hayley Hughes

2024-04-02 07:06 UTC, omckeon commented on src/content/docs/teams-and-leadership/team-members-t1-2024.md
> +| James Stuart Balsillie   | Team member  | Code, Documentation                  |
Update this name to be: Jess Balsillie

2024-04-14 08:50 UTC, omckeon approved these changes
Much better :) Thanks!

2024-04-14 08:50 UTC, merged