Docs: Add getting started guide to Ontrack
thoth-tech/ThothTech-Documentation-Website pull request #83
Opened 2024-07-26 03:46 UTC by JoshuaBourquin

# Description

This change adds a beginner guide for OnTrack, which talks through the setup process to start contributing and likely errors they may face. It also includes links to libraries and packages that OnTrack uses as well as a general overview of the system.

## Type of change

- [x] Documentation (update or new)

## Testing Checklist

- [x] Tested in latest Chrome
- [ ] Tested in latest Safari
- [x] Tested in latest Firefox

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have requested a review from ... on the Pull Request

2024-07-28 08:07 UTC, satikaj requested changes
Great work overall! It looks good.

Could you please just address my comments and push the changes? Thanks

2024-07-28 08:07 UTC, satikaj commented on src/content/docs/products/ontrack/start-contributing.md
> +Sometimes if you are having any weird Docker container related problems such as shown below, you might need to delete all **Containers, Images, and Volumes** related to **doubtfire-lms/formatif** fro
Please also add a reminder to check if any updates are pending for Docker. Not updating the app might disrupt it's behaviour as well.

2024-07-28 08:07 UTC, satikaj commented on src/content/docs/products/ontrack/start-contributing.md
> +Currently, ThothTech has 2 documentation repositories, [ThothTech/documentation](https://github.com/thoth-tech/documentation) and [ThothTech/ThothTech-Documentation-Website](https://github.com/thoth-
This part needs to be changed. documentation is for internal docs, anything we can't release to the public like docs about new features we are working on. ThothTech-Documentation-Website is the external docs repo, anything we have that helps introduce new members into the company and products

2024-11-06 02:23 UTC, omckeon approved these changes

2024-11-06 02:25 UTC, merged